#staging
deployment:
    user: matiux
    from: ./
    to: /var/www/Project/RufyApi
    excludes:
        - .idea
        - composer.lock
        - rufysf.conf
        - spec
releases:
    enabled: true
    max: 3
    symlink: current
    directory: releases
hosts:
    - 46.101.237.153
tasks:
    pre-deploy:
    on-deploy:
    post-release:
    post-deploy:
        - clear-cache
        - permissions-set-dirs
        - database-clear
        - database-create
        - database-populate
        - composer-optimize
        - symfony2/cache-clear: {env: prod}
        - symfony2/cache-warmup: {env: prod}
        - symfony2/cache-clear: {env: dev}
        - symfony2/cache-warmup: {env: dev}
