rufy_rest_api_dev:
    resource: "@RufyRestApiDevBundle/Resources/config/routing.yml"
    prefix:   /test

rufy_rest_api:
    type: rest
    prefix: /api
    resource: "@RufyRestApiBundle/Resources/config/routing.yml"

rufy_command:
    prefix: /command
    resource: "@RufyRestApiBundle/Resources/config/routing_command.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
