rufy_rest_api_home:
    path:     /
    defaults: { _controller: RufyRestApiBundle:Default:index }


reservations:
    type: rest
    prefix: v1
    resource: Rufy\RestApiBundle\Controller\ReservationController
    name_prefix:  api_v1_

restaurants:
    type: rest
    prefix: v1
    resource: Rufy\RestApiBundle\Controller\RestaurantController
    name_prefix:  api_v1_

areas:
    type: rest
    prefix: v1
    resource: Rufy\RestApiBundle\Controller\AreaController
    name_prefix:  api_v1_
