parameters:
    rufy_api.reservation.handler.class: Rufy\RestApiBundle\Handler\Db\Doctrine\ReservationHandler
    rufy_api.restaurant.handler.class: Rufy\RestApiBundle\Handler\Db\Doctrine\RestaurantHandler
    rufy_api.area.handler.class: Rufy\RestApiBundle\Handler\Db\Doctrine\AreaHandler
    rufy_api.customer.handler.class: Rufy\RestApiBundle\Handler\Db\Doctrine\CustomerHandler

    rufy_api.reservation.class: Rufy\RestApiBundle\Entity\Reservation
    rufy_api.restaurant.class: Rufy\RestApiBundle\Entity\Restaurant
    rufy_api.area.class: Rufy\RestApiBundle\Entity\Area
    rufy_api.customer.class: Rufy\RestApiBundle\Entity\Customer

services:

    string:
        class: Rufy\RestApiBundle\Utility\String

    ###########################################
    ## Listeners
#    rufy_api.authenticated.fully.listener:
#        class: Rufy\RestApiBundle\EventListener\AuthenticatedFullyListener
#        arguments: [@service_container]
#        tags:
#            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}
    ## Fine Listeners
    #############################################

    ###########################################
    ## Modelli
    rufy_api.reservation.class:
        class: %rufy_api.reservation.class%

    rufy_api.restaurant.class:
        class: %rufy_api.restaurant.class%

    rufy_api.area.class:
        class: %rufy_api.area.class%

    rufy_api.customer.class:
        class: %rufy_api.customer.class%

    ## Fine Modelli
    #############################################

    ###########################################
    ## Handler dei modelli
    rufy_api.entity_handler:
        abstract: true
        calls:
            - [setObjectManagerAndEntity, [@doctrine.orm.entity_manager]]
            - [setUser, [@security.token_storage]]
            - [setAuthorizationChecker, [@security.authorization_checker]]
            - [setFormFactory, [@form.factory]]

    rufy_api.reservation.handler:
        class: %rufy_api.reservation.handler.class%
        parent: rufy_api.entity_handler
        calls:
            - [setEntityClass, [@rufy_api.reservation.class]]

    rufy_api.restaurant.handler:
        class: %rufy_api.restaurant.handler.class%
        parent: rufy_api.entity_handler
        calls:
            - [setEntityClass, [@rufy_api.restaurant.class]]

    rufy_api.area.handler:
        class: %rufy_api.area.handler.class%
        parent: rufy_api.entity_handler
        calls:
            - [setEntityClass, [@rufy_api.area.class]]

    rufy_api.customer.handler:
        class: %rufy_api.customer.handler.class%
        parent: rufy_api.entity_handler
        calls:
            - [setEntityClass, [@rufy_api.customer.class]]

    ## Fine Handler dei modelli
    #############################################

    ###########################################
    # Form
    rufy_api.form.type.reservation:
        class: Rufy\RestApiBundle\Form\ReservationType
        arguments: [@security.token_storage]
        tags:
            - {name: form.type, alias: reservation_type }

    rufy_api.form.type.customer:
        class: Rufy\RestApiBundle\Form\CustomerType
        arguments: [@security.token_storage]
        tags:
            - {name: form.type, alias: customer_type }

    rufy_api.form.type.restaurant:
        class: Rufy\RestApiBundle\Form\RestaurantType
        arguments: [@security.token_storage]
        tags:
            - {name: form.type, alias: restaurant_type }
    ## Fine Form
    #############################################

    ###########################################
    # Transformer
    rufy_api.reservation.transformer:
        class: Rufy\RestApiBundle\Transformer\Fractal\ReservationTransformer

    rufy_api.custom.fractal.serializer:
        class: Rufy\RestApiBundle\Transformer\Fractal\Serializer\CustomSerializer
    ## Fine Transformer
    #############################################

    ###########################################
    ##  Custom Serializer per FosRestBundle
    rufy_api.fosrest_serializer:
        class: Rufy\RestApiBundle\Handler\Serializer\RufySerializerHandler
        arguments: [@sam_j_fractal.manager, @rufy_api.custom.fractal.serializer]

    ###########################################
    ##  Voter
    security.access.voter:
        abstract: true
        calls:
            - [setObjectManager, [@doctrine.orm.entity_manager]]

    security.access.area.voter:
        class:      Rufy\RestApiBundle\Security\Authorization\Voter\AreaVoter
        parent:     security.access.voter
        tags:
            - { name: security.voter }

    security.access.customer.voter:
        class:      Rufy\RestApiBundle\Security\Authorization\Voter\CustomerVoter
        parent:     security.access.voter
        tags:
            - { name: security.voter }

    security.access.restaurant.voter:
        class:      Rufy\RestApiBundle\Security\Authorization\Voter\RestaurantVoter
        parent:     security.access.voter
        tags:
            - { name: security.voter }

    security.access.reservation.voter:
        class:      Rufy\RestApiBundle\Security\Authorization\Voter\ReservationVoter
        parent:     security.access.voter
        tags:
            - { name: security.voter }
