parameters:
    rufy_api.reservation.handler.class: Rufy\RestApiBundle\Handler\Db\Doctrine\ReservationHandler
    rufy_api.restaurant.handler.class: Rufy\RestApiBundle\Handler\Db\Doctrine\RestaurantHandler
    rufy_api.reservation.class: Rufy\RestApiBundle\Entity\Reservation
    rufy_api.restaurant.class: Rufy\RestApiBundle\Entity\Restaurant

services:

    string:
        class: Rufy\RestApiBundle\Utility\String

    ###########################################
    ## Modelli
    rufy_api.reservation.class:
        class: %rufy_api.reservation.class%

    rufy_api.restaurant.class:
        class: %rufy_api.restaurant.class%

    ## Fine Modelli
    #############################################

    ###########################################
    ## Handler dei modelli
    rufy_api.entity_handler:
        abstract: true
        calls:
            - [setObjectManagerAndEntity, [@doctrine.orm.entity_manager]]
            - [setUser, [@security.token_storage]]
            - [setAuthorizationChecker, [@security.authorization_checker]]

    rufy_api.reservation.handler:
        class: %rufy_api.reservation.handler.class%
        parent: rufy_api.entity_handler
        calls:
            - [setEntityClass, [@rufy_api.reservation.class]]

    rufy_api.restaurant.handler:
        class: %rufy_api.restaurant.handler.class%
        parent: rufy_api.entity_handler
        calls:
            - [setEntityClass, [@rufy_api.restaurant.class]]

    ## Fine Handler dei modelli
    #############################################


    ###########################################
    # Transformer
    rufy_api.reservation.transformer:
        class: Rufy\RestApiBundle\Transformer\Fractal\ReservationTransformer

    rufy_api.custom.fractal.serializer:
        class: Rufy\RestApiBundle\Transformer\Fractal\Serializer\CustomSerializer
    ## Fine Transformer
    #############################################

    ###########################################
    ##  Custom Serializer per FosRestBundle
    rufy_api.fosrest_serializer:
        class: Rufy\RestApiBundle\Handler\Serializer\RufySerializerHandler
        arguments: [@sam_j_fractal.manager, @rufy_api.custom.fractal.serializer]

    ###########################################
    ##  Voter
    security.access.reservation.voter:
        class:      Rufy\RestApiBundle\Security\Authorization\Voter\ReservationVoter
        arguments:  [@doctrine.orm.entity_manager]
        public:     false
        tags:
            - { name: security.voter }

    security.access.restaurant.voter:
        class:      Rufy\RestApiBundle\Security\Authorization\Voter\RestaurantVoter
        arguments:  [@doctrine.orm.entity_manager]
        public:     false
        tags:
            - { name: security.voter }
