parameters:
    rufy_api.reservation.handler.class: Rufy\RestApiBundle\Handler\ReservationHandler
    rufy_api.reservation.class: Rufy\RestApiBundle\Entity\Reservation

services:
#    rufy_rest_api.example:
#        class: Rufy\RestApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    string:
        class: Rufy\RestApiBundle\Utility\String

    rufy_api.reservation.handler:
        class: "%rufy_api.reservation.handler.class%"
        arguments: ["@doctrine.orm.entity_manager", "%rufy_api.reservation.class%"]

    rufy_api.reservation.json_handler:
        class: Rufy\RestApiBundle\Response\View\JsonViewHandler

    rufy_api.reservation.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'json', [@rufy_api.reservation.json_handler, 'createResponse'] ] ]
