parameters:
    rufy_api.reservation.handler.class: Rufy\RestApiBundle\Handler\Db\Doctrine\ReservationHandler
    rufy_api.reservation.class: Rufy\RestApiBundle\Entity\Reservation

services:
#    rufy_rest_api.example:
#        class: Rufy\RestApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    string:
        class: Rufy\RestApiBundle\Utility\String

    rufy_api.custom.fractal.serializer:
        class: Rufy\RestApiBundle\Transformer\Fractal\Serializer\CustomSerializer

    ###########################################
    ## Modelli

    rufy_api.reservation.class:
        class: %rufy_api.reservation.class%

    ## Fine Modelli
    #############################################

    ###########################################
    ## Handler dei modelli

    rufy_api.reservation.handler:
        class: %rufy_api.reservation.handler.class%
        arguments: [@doctrine.orm.entity_manager, @rufy_api.reservation.class, @security.context]
    ## Fine Handler dei modelli

    #############################################


    ###########################################
    # Transformer
    rufy_api.reservation.transformer:
        class: Rufy\RestApiBundle\Transformer\Fractal\ReservationTransformer
    ## Fine Transformer
    #############################################

    ###########################################
    ##  Custom Serializer per FosRestBundle
    rufy_api.fosrest_serializer:
        class: Rufy\RestApiBundle\Handler\Serializer\RufySerializerHandler
        arguments: [@sam_j_fractal.manager, @rufy_api.custom.fractal.serializer]

    ###########################################
    ##  Voter
    security.access.reservation_voter:
        class:      Rufy\RestApiBundle\Security\Authorization\Voter\ReservationVoter
        arguments:  [@doctrine.orm.entity_manager]
        public:     false
        tags:
            - { name: security.voter }
