Rufy\RestApiBundle\Entity\Restaurant:
  properties:
    id:
      - Type:
          type: integer
          message: area_id deve essere passato come integer
    name:
      - Type:
          type: string
          message: note deve essere passato come string
    rest_date:
      - Type:
          type: integer
          message: area_id deve essere passato come integer

Rufy\RestApiBundle\Entity\Reservation:
  properties:
    area:
      - NotBlank: ~
      - Type:
          type: integer
          message: area_id deve essere passato come integer
      - GreaterThan:
          value: 0
          message: "Area id non valido"
    customer:
      - NotBlank: ~
      - Type:
          type: integer
          message: customer_id deve essere passato come integer
      - GreaterThan:
          value: 0
          message: "Customer id non valido"
    people:
      - NotBlank: ~
      - Type:
          type: integer
          message: people deve essere passato come integer
      - GreaterThan:
          value: 0
          message: "Numero persone non valido non valido"
    time:
      - NotBlank: ~
      - Time:
          message: "Formato ora non valido. Usare HH:MM:SS"
    date:
      - NotBlank: ~
      - Date:
          message: "Formato data non valido. Usare YYYY-MM-DD"
    confirmed:
      - NotBlank: ~
      - Type:
          type: bool
          message: confirmed deve essere passato come bool
    waiting:
      - NotBlank: ~
      - Type:
          type: bool
          message: waiting deve essere passato come bool
    note:
      - Type:
          type: string
          message: note deve essere passato come string
    table_name:
      - Type:
          type: string
          message: table_name deve essere passato come string

#Rufy\RestApiBundle\Entity\Reservation:
#  getters:
#    passwordLegal:
#      - "True": { message: "La password non può essere uguale allo username o alla email" }
#  properties:
#    username:
#      - NotBlank: ~
#      - NotNull: ~
#      - Length:
#          min: 3
