Rufy\RestApiBundle\Entity\Customer:
  properties:
    name:
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    phone:
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    email:
      - Email:
          message: The email "{{ value }}" is not a valid email.
          checkMX: true
    privacy:
      - Type:
          type: bool
          message: Il valore {{ value }} non è un {{ type }} valido.
    newsletter:
      - Type:
          type: bool
          message: Il valore {{ value }} non è un {{ type }} valido.
    restaurant:
      - NotNull:
          message: Indicare il ristorante del Customer.

Rufy\RestApiBundle\Entity\Area:
  properties:
    name:
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    maxPeople:
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
    restaurant:
      - NotNull:
          message: Indicare il ristorante del Customer.

Rufy\RestApiBundle\Entity\Restaurant:
  properties:
    name:
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    rest_date:
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.

Rufy\RestApiBundle\Entity\Reservation:
  properties:
    people:
      - NotBlank:
          message: Inserire il numero di persone
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
      - GreaterThan:
          value: 0
          message: Il numero persone deve essere maggiore di zero
    people_extra:
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
    note:
      - Type:
          type: string
          message: note deve essere passato come string
    status:
      - NotBlank:
          message: Status deve essere fornito
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
    table_name:
      - NotBlank:
          message: Inserire il tavolo
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    customer:
      - NotBlank:
          message: Seleziona un cliente
    area:
      - NotBlank:
          message: Indicare l'area della prenotazione
#    reservationOptions:
#      - Collection:
#          fields:
#              slug:
#                  - Type:
#                      type: string
#                      message: note deve essere passato come string
#          allowMissingFields: true
