Rufy\RestApiBundle\Entity\Area:
  properties:
    id:
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
    name:
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    restaurant:
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
    full:
      - Type:
          type: bool
          message: Il valore {{ value }} non è un {{ type }} valido.

Rufy\RestApiBundle\Entity\Restaurant:
  properties:
    id:
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
    name:
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    rest_date:
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.

Rufy\RestApiBundle\Entity\Reservation:
  properties:
    people:
      - NotBlank:
          message: Inserire il numero di persone
      - Type:
          type: integer
          message: Il valore {{ value }} non è un {{ type }} valido.
      - GreaterThan:
          value: 0
          message: "Il numero persone deve essere maggiore di zero"
#    time:
#      - Time:
#          message: Il valore {{ value }} non è un {{ type }} valido.
#      - NotBlank:
#          message: E' necessario impostare l'orario della prenotazione nel formato HH:MM:SS"
#    date:
#      - Type:
#          type: \DateTime
#          message: Il valore {{ value }} non è un {{ type }} valido.
#      - NotBlank:
#          message: Impostare la data
#      - Date:
#          message: "Formato data non valido. Usare YYYY-MM-DD"
    note:
      - Type:
          type: string
          message: note deve essere passato come string
    confirmed:
      - NotBlank:
          message: Confirmed deve essere fornito, 0 o 1
      - Type:
          type: bool
          message: Il valore {{ value }} non è un {{ type }} valido.
    waiting:
      - NotBlank:
          message: Waiting deve essere fornito, 0 o 1
      - Type:
          type: bool
          message: Il valore {{ value }} non è un {{ type }} valido.
    table_name:
      - NotBlank:
          message: Inserire il tavolo
      - Type:
          type: string
          message: Il valore {{ value }} non è un {{ type }} valido.
    customer:
      - NotBlank:
          message: Seleziona un cliente
#      - Type:
#          type: integer
#          message: Il valore {{ value }} non è un {{ type }} valido.
#      - GreaterThan:
#          value: 0
#          message: Customer id non valido
    area:
      - NotBlank:
          message: Indicare l'area della prenotazione
#      - Type:
#          type: integer
#          message: Il valore {{ value }} non è un {{ type }} valido.
#      - GreaterThan:
#          value: 0
#          message: "Area id non valido"
#    reservationOptions:
#      - Collection:
#          fields:
#              slug:
#                  - Type:
#                      type: string
#                      message: note deve essere passato come string
#          allowMissingFields: true

#    user:
#      - NotBlank:
#          message: E' necessario indicare un utente
#      - Type:
#          type: integer
#          message: Il valore {{ value }} non è un {{ type }} valido.
#      - GreaterThan:
#          value: 0
#          message: "User id non valido"

#Rufy\RestApiBundle\Entity\Reservation:
#  getters:
#    passwordLegal:
#      - "True": { message: "La password non può essere uguale allo username o alla email" }
#  properties:
#    username:
#      - NotBlank: ~
#      - NotNull: ~
#      - Length:
#          min: 3
