Rufy\RestApiBundle\Entity\Reservation:
    exclusion_policy: ALL
    virtual_properties:
        getAreaId:
            serialized_name: area
            type: integer
    properties:
        id:
            expose: true
        people:
            expose: true
        people_extra:
            expose: true
        time:
            expose: true
            type: DateTime<'H:m'>
        date:
            expose: true
            type: DateTime<'Y-m-d'>
        note:
            expose: true
        status:
            expose: true
        table_name:
            expose: true
        customer:
            expose: true

