Rufy\RestApiBundle\Entity\Reservation:
    exclusion_policy: ALL
    xml_root_name: reservation
    virtual_properties:
        getCustomer:
            serialized_name: name
            type: string
            xml_map:
                inline: true
                key_attribute_name: name
                entry_name: name
    properties:
        id:
            expose: true
        people:
            expose: true
        confirmed:
            expose: true

