Rufy\RestApiBundle\Entity\Reservation:
    exclusion_policy: ALL
    xml_root_name: reservation
    properties:
        id:
            expose: true
            since_version: v1
        people:
            expose: true
            since_version: v1
        confirmed:
            expose: true
            since_version: v1

